export const steps = [
    "start",
    "ageSex",
    "bpInstructions",
    "bp",
    "heightInstructions",
    "height",
    "weightInstructions",
    "weight",
    "summary",
    "diabetesIntro",
    "diabetesFirst",
    "diabetesSecond",
    "diabetesThird",
    "diabetesSummary",
    "diabetesResults",
    "miniEatIntro",
    "miniEatQuestion1",
    "miniEatQuestion2",
    "miniEatQuestion3",
    "miniEatQuestion4",
    "miniEatQuestion5",
    "miniEatQuestion6",
    "miniEatQuestion7",
    "miniEatQuestion8",
    "miniEatQuestion9",
    "miniEatSummary",
    "miniEatResults",
] as const;

export type Step = (typeof steps)[number];

export const skipTargets: Partial<Record<Step, Step>> = {
    diabetesIntro: "summary",
    diabetesFirst: "diabetesThird",
    diabetesSecond: "diabetesThird",
    diabetesThird: "diabetesIntro",
    miniEatIntro: "diabetesResults",
    miniEatQuestion1: "diabetesResults",
    miniEatQuestion2: "diabetesResults",
    miniEatQuestion3: "diabetesResults",
    miniEatQuestion4: "diabetesResults",
    miniEatQuestion5: "diabetesResults",
    miniEatQuestion6: "diabetesResults",
    miniEatQuestion7: "diabetesResults",
    miniEatQuestion8: "diabetesResults",
    miniEatQuestion9: "diabetesResults",
    miniEatSummary: "diabetesResults",
};
